import fs from "node:fs/promises";
import path from "node:path";
import type OpenAI from "openai";
import type { Evidence } from "../domain/types";
export interface VectorDocument { id: string; source: string; content: string; embedding: number[]; }
export interface EmbeddingProvider { embed(texts: string[]): Promise<number[][]>; }
export function chunkText(text: string, size = 1200, overlap = 200) { if (overlap >= size) throw new Error("El solapamiento debe ser menor al tamaño del chunk."); const chunks: string[] = []; for (let start = 0; start < text.length; start += size - overlap) chunks.push(text.slice(start, start + size)); return chunks.filter((chunk) => chunk.trim()); }
export class OpenAIEmbeddingProvider implements EmbeddingProvider { constructor(private readonly client: OpenAI, private readonly model: string) {} async embed(texts: string[]) { const result = await this.client.embeddings.create({ model: this.model, input: texts }); return result.data.map((item) => item.embedding); } }
function cosine(left: number[], right: number[]) { let dot = 0, a = 0, b = 0; for (let index = 0; index < left.length; index++) { dot += left[index] * right[index]; a += left[index] ** 2; b += right[index] ** 2; } return dot / (Math.sqrt(a) * Math.sqrt(b) || 1); }
export class RagService { constructor(private readonly file: string, private readonly embeddings: EmbeddingProvider) {} private async read() { try { return JSON.parse(await fs.readFile(this.file, "utf8")) as VectorDocument[]; } catch { return []; } } async index(sources: { source: string; content: string }[]) { const chunks = sources.flatMap((source) => chunkText(source.content).map((content, index) => ({ id: `${source.source}#${index}`, source: source.source, content }))); const vectors = await this.embeddings.embed(chunks.map((chunk) => chunk.content)); const documents = chunks.map((chunk, index) => ({ ...chunk, embedding: vectors[index] })); await fs.mkdir(path.dirname(this.file), { recursive: true }); await fs.writeFile(this.file, JSON.stringify(documents), "utf8"); return documents.length; } async search(query: string, limit = 4): Promise<Evidence[]> { const [vector] = await this.embeddings.embed([query]); return (await this.read()).map((document) => ({ document, score: cosine(vector, document.embedding) })).sort((a, b) => b.score - a.score).slice(0, limit).map(({ document }) => ({ origin: "rag", document: document.source, excerpt: document.content, location: document.id })); } }
