import readline from "node:readline/promises"; import path from "node:path"; import { stdin as input, stdout as output } from "node:process"; import type { ResponseInputItem } from "openai/resources/responses/responses"; import { runAgentTurn, createAgent } from "./agent/harness"; import { llm } from "./llm/client"; import { loadSources, readSourceManifest } from "./rag/sources"; import { MemoryService } from "./services/memory";
const rl = readline.createInterface({ input, output }); const conversation: ResponseInputItem[] = []; const state = { mode: "normal" as "normal" | "planning", supervisionMode: true };
async function confirmAction(message: string) { console.log(`\nAcción supervisada:\n${message}`); return (await rl.question("¿Permitir? [y/n]: ")).trim().toLowerCase() === "y"; }
function printHelp() { console.log("Coding Agent Avanzado iniciado.\nComandos: /plan on|off, /supervision on|off, /config, /memory, /rag index, /status, /help, /exit"); }
async function handleCommand(value: string) { const command = value.trim(); if (command === "/exit") return "exit"; if (command === "/help") { printHelp(); return "handled"; } if (command === "/plan on" || command === "/plan off") { state.mode = command.endsWith("on") ? "planning" : "normal"; console.log(`Plan mode ${state.mode === "planning" ? "activado" : "desactivado"}.`); return "handled"; } if (command === "/supervision on" || command === "/supervision off") { state.supervisionMode = command.endsWith("on"); console.log(`Supervisión ${state.supervisionMode ? "activada" : "desactivada"}.`); return "handled"; } if (["/config", "/memory", "/rag index", "/status"].includes(command)) { const agent = await createAgent(process.cwd(), { supervisionMode: state.supervisionMode, confirmAction }); if (command === "/config") console.log(JSON.stringify(agent.config, null, 2)); if (command === "/memory") console.log(JSON.stringify(await new MemoryService(path.resolve(process.cwd(), agent.config.paths.memory)).read(path.basename(process.cwd())), null, 2)); if (command === "/status") console.log(JSON.stringify(await agent.states.latest(), null, 2)); if (command === "/rag index") console.log(`Chunks indexados: ${await agent.rag.index(await loadSources(process.cwd(), await readSourceManifest(process.cwd())))}`); return "handled"; } return "not-command"; }
async function execute(request: string) { const result = await runAgentTurn(request, conversation, { supervisionMode: state.supervisionMode, confirmAction }); console.log(`\nAgente:\n${result.finalText}\n\nIteraciones: ${result.iterations}`); }
async function planningTurn(request: string) { let feedback = ""; while (true) { const agent = await createAgent(process.cwd(), { supervisionMode: false }); const response = await llm.responses.create({ model: agent.config.model, instructions: "Sos un planning agent. Proponé solamente un plan numerado, sin ejecutar ni afirmar cambios.", input: `${request}${feedback ? `\n\nFeedback: ${feedback}` : ""}` }); console.log(`\nPlan:\n${response.output_text}`); if ((await rl.question("\n¿Aprobás el plan? [y/n/modificar]: ")).trim().toLowerCase() === "y") return execute(request); feedback = await rl.question("Indicá qué querés modificar: "); } }
async function main() { printHelp(); while (true) { const userInput = await rl.question("\nUsuario: "); const result = await handleCommand(userInput); if (result === "exit") break; if (result === "handled") continue; if (state.mode === "planning") await planningTurn(userInput); else await execute(userInput); } rl.close(); }
main().catch((error) => { console.error("Error fatal:", error); process.exitCode = 1; rl.close(); });
