import fs from "node:fs/promises"; import path from "node:path"; import { exec } from "node:child_process"; import { promisify } from "node:util"; import { z } from "zod"; import type OpenAI from "openai"; import type { AgentRole } from "../domain/types"; import { MemoryService, type ProjectMemory } from "../services/memory"; import { PolicyService } from "../services/policy"; import { RagService } from "../services/rag"; import { ToolRegistry, type AgentTool } from "./tool";
const execAsync = promisify(exec); const all: AgentRole[] = ["explorer", "researcher", "implementer", "tester", "reviewer"]; const parameters = (properties: Record<string, unknown>, required: string[]) => ({ type: "object", properties, required, additionalProperties: false }); const define = <T>(tool: AgentTool<T>) => tool;
export interface ToolServices { root: string; policy: PolicyService; memory: MemoryService; rag: RagService; client: OpenAI; model: string; project: string; confirm?: (message: string) => Promise<boolean>; modifiedFiles: Set<string>; }
export function buildToolRegistry(s: ToolServices) { const registry = new ToolRegistry();
registry.register(define({ name: "read_file", description: "Lee un archivo del proyecto.", effect: "read", allowedRoles: all, schema: z.object({ path: z.string() }), parameters: parameters({ path: { type: "string" } }, ["path"]), async execute(args) { return { path: args.path, content: await fs.readFile(s.policy.validatePath(args.path, "read"), "utf8"), origin: "repository" }; } }));
registry.register(define({ name: "list_files", description: "Lista un directorio del proyecto.", effect: "read", allowedRoles: ["explorer", "implementer", "reviewer"], schema: z.object({ path: z.string() }), parameters: parameters({ path: { type: "string" } }, ["path"]), async execute(args) { const entries = await fs.readdir(s.policy.validatePath(args.path, "read"), { withFileTypes: true }); return { files: entries.map((entry) => ({ name: entry.name, type: entry.isDirectory() ? "directory" : "file" })), origin: "repository" }; } }));
registry.register(define({ name: "search_text", description: "Busca texto en el repositorio.", effect: "read", allowedRoles: ["explorer", "researcher", "implementer", "reviewer"], schema: z.object({ query: z.string(), path: z.string() }), parameters: parameters({ query: { type: "string" }, path: { type: "string" } }, ["query", "path"]), async execute(args) { const directory = s.policy.validatePath(args.path, "read"); const result = await execAsync(`rg --line-number --glob !node_modules --glob !.agent-data ${JSON.stringify(args.query)} ${JSON.stringify(directory)}`, { cwd: s.root, timeout: 15_000 }).catch((error) => ({ stdout: error.stdout ?? "" })); return { matches: result.stdout.slice(0, 20_000), origin: "repository" }; } }));
registry.register(define({ name: "write_file", description: "Reemplaza un archivo validando políticas.", effect: "write", allowedRoles: ["implementer"], schema: z.object({ path: z.string(), content: z.string() }), parameters: parameters({ path: { type: "string" }, content: { type: "string" } }, ["path", "content"]), async execute(args) { const file = s.policy.validatePath(args.path, "write"); await fs.mkdir(path.dirname(file), { recursive: true }); await fs.writeFile(file, args.content, "utf8"); s.modifiedFiles.add(args.path); return { success: true, path: args.path }; } }));
registry.register(define({ name: "run_command", description: "Ejecuta un comando permitido.", effect: "command", allowedRoles: ["explorer", "implementer", "tester"], schema: z.object({ command: z.string() }), parameters: parameters({ command: { type: "string" } }, ["command"]), async execute(args) { const policy = s.policy.commandPolicy(args.command); if (policy.requiresApproval && !(await s.confirm?.(`¿Permitir comando: ${args.command}?`))) return { rejected: true }; try { const result = await execAsync(args.command, { cwd: s.root, timeout: 30_000 }); return { ...result, exitCode: 0 }; } catch (error: any) { return { stdout: error.stdout ?? "", stderr: error.stderr ?? error.message, exitCode: Number(error.code) || 1 }; } } }));
registry.register(define({ name: "git_diff", description: "Obtiene el diff actual.", effect: "read", allowedRoles: ["implementer", "reviewer"], schema: z.object({}), parameters: parameters({}, []), async execute() { const result = await execAsync("git diff --no-ext-diff", { cwd: s.root, timeout: 10_000 }).catch((error) => ({ stdout: error.stdout ?? "", stderr: error.stderr ?? error.message })); return { diff: result.stdout.slice(0, 30_000), stderr: result.stderr }; } }));
registry.register(define({ name: "query_rag", description: "Recupera documentación indexada.", effect: "read", allowedRoles: ["researcher", "implementer"], schema: z.object({ query: z.string() }), parameters: parameters({ query: { type: "string" } }, ["query"]), async execute(args) { return { evidence: await s.rag.search(args.query) }; } }));
registry.register(define({ name: "read_memory", description: "Lee memoria persistente.", effect: "memory", allowedRoles: all, schema: z.object({}), parameters: parameters({}, []), async execute() { return { origin: "memory", memory: await s.memory.read(s.project) }; } }));
registry.register(define({ name: "update_memory", description: "Agrega conocimiento confirmado.", effect: "memory", allowedRoles: ["explorer", "researcher", "reviewer"], schema: z.object({ patch: z.record(z.string(), z.array(z.string())) }), parameters: parameters({ patch: { type: "object", additionalProperties: { type: "array", items: { type: "string" } } } }, ["patch"]), async execute(args) { return s.memory.update(s.project, args.patch as Partial<ProjectMemory>); } }));
registry.register(define({ name: "web_search", description: "Fallback web; prioriza documentación oficial.", effect: "network", allowedRoles: ["researcher"], schema: z.object({ query: z.string() }), parameters: parameters({ query: { type: "string" } }, ["query"]), async execute(args) { const response = await s.client.responses.create({ model: s.model, input: `Buscá ${args.query}. Priorizá documentación oficial y devolvé URLs.`, tools: [{ type: "web_search" }] }); return { origin: "web", result: response.output_text }; } })); return registry; }
